id: P002905
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 10:27:32.925756
source_metadata:
  id: bdr:W1KG25578
  title: ཇོ་བོ་རྗེ་དཔལ་ལྡན་ཨ་ཏི་ཤའི་རྣམ་ཐར་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    6510298fccc54dfda83e42792b32763f:
      image_group_id: I1KG25580
      title: ''
      volume_number: 1
      total_pages: 702
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
